# Use latest Node LTS to build
FROM node:lts as builder
# Copy Vue.js code
WORKDIR /app
COPY webui webui
WORKDIR /app/webui
### Build production
RUN npm run build-prod
### Create final container
FROM nginx:stable
### Copy the built app from image
COPY --from=builder /app/webui/dist /usr/share/nginx/html