# Starting image
FROM golang:1.19.1 AS builder
# Copy Go code into workdir
WORKDIR /src/
COPY . .
# Build executables (in "builder")
RUN go build -o /app/webapi ./cmd/webapi
# Create final container
FROM debian:bookworm
# Inform Docker about which port is used
EXPOSE 3000
# Copy the executable from the "builder" image
WORKDIR /app/
COPY --from=builder /app/webapi ./
# Set default program
CMD ["/app/webapi"]