openapi: 3.0.2
info:
  description: API for WasaPhoto project
  version: 1.0.0
  title: WasaPhoto API
  contact:
    email: matiddi.1985899@studenti.uniroma1.it

paths:
  /session/:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: "Ë†.*?$"
                  minLength: 3
                  maxLength: 16
      responses:
        "201":
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    # change here if you decide to use an integer
                    # or any other type of identifier
                    type: string
                    example: "abcdef012345"
  /photos/:
    put:
      operationId: uploadPhoto
      summary: Upload a new photo
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                caption:
                  type: string
                  description: The caption of the photo
                file:
                  type: string
                  format: binary
                  description: The photo file
      responses:
        "201":
          description: Photo uploaded successfully.
          content:
            application/json:
              schema: { $ref: "#/components/schemas/Photo" }
        "400":
          description: Bad request
          content:
            application/json:
              example:
                error: "Invalid request. Please provide a caption and a photo file."
  /photos/{photoId}/:
    delete:
      operationId: deletePhoto
      summary: Delete a photo that exists.
      parameters:
        - $ref: "#/components/parameters/photoId"
      responses:
        "201":
          description: Photo deleted successfully.
        "404":
          description: Photo not found.
  /users/:
    put:
      operationId: createUser
      summary: Create new user profile.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Name of the new user.
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema: { $ref: "#/components/schemas/User" }
        "400":
          description: Bad Request
  /users/{userId}/:
    delete:
      operationId: createUser
      summary: Create new user profile.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to delete.
          schema:
            type: integer
      responses:
        "201":
          description: Deleted
        "400":
          description: Bad Request
        "404":
          description: User not found
  /user/{userId}/follows/:
    put:
      summary: Follow a user.
      operationId: followUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: integer
                  description: Id of the new followed user.
      responses:
        "200":
          description: Follow successful.
        "400":
          description: Bad Request.
        "404":
          description: User not found.
  /user/{userId}/follows/{userId}:
    delete:
      summary: Unfollow a user.
      operationId: unfollowUser
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to unfollow.
          schema:
            type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: User not found

components:
  parameters:
    photoId:
      in: path
      name: photoId
      required: true
      schema:
        type: integer
    userId:
      in: path
      name: userId
      required: true
      schema:
        type: integer
  schemas:
    User:
      title: User
      description: User profile of a user.
      type: object
      required:
        - name
      properties:
        id:
          description: User identifier, uniquely generated.
          type: integer
          example: 32132131
          readOnly: true
        name:
          description: Name of the user.
          type: string
          example: Gabriele Matiddi
        followers:
          description: Followers of the user.
          type: array
          items:
            type: integer
            description: Ids of the users that follow the user.
        banned:
          description: Users banned from profile of the user.
          type: array
          items:
            type: integer
            description: Ids of the users that are banned by the user.

    Photo:
      title: Photo
      description: This object represents a photo in the system.
      type: object
      properties:
        id:
          description: Photo identifier, uniquely generated.
          type: integer
          example: 123456
          readOnly: true
        image_content:
          description: Content of the photo.
          type: string
          format: base64
          example: EXAMPLE HERE
        releaseDate:
          type: string
          description: Date and time of photo publication.
          format: date-time
          example: "2016-08-29T09:12:33.001Z"
        caption:
          description: Photo caption written by the user.
          type: string
          example: Bella giornata!
        publisher:
          description: Publisher of the photo.
          type: string
        likes:
          description: Likes of the photo.
          type: integer
          example: 123

    Comment:
      title: Comment
      description: Comment of a published photo.
      type: object
      properties:
        id:
          description: Comment unique identifier.
          type: integer
          example: 1234
        content:
          description: Text content of the comment.
          type: string
          example: Nice photo!
        publisher:
          description: User that published the comment
          $ref: "#/components/schemas/User"
