openapi: 3.0.2
info:
  description: API for WasaPhoto project
  version: 1.0.0
  title: WasaPhoto API
  contact:
    email: matiddi.1985899@studenti.uniroma1.it
servers:
  - url: http://localhost:3000

tags:
  - name: photos
    description: All related to photos
  - name: users
    description: All related to users
  - name: comments
    description: All related to comments
  - name: likes
    description: All related to likes
  - name: follows
    description: All related to follows
  - name: bans
    description: All related to bans
  - name: login
    description: All related to login

paths:
  /session/:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: string
              example: Maria
              pattern: ".*"
              description: Username of the user
              minLength: 3
              maxLength: 16
      responses:
        "201":
          $ref: "#/components/responses/Created"
    get:
      summary: Get user profile by name
      description: Retrieve user Id.
      operationId: getUserProfile
      tags:
        - users
      requestBody:
        required: true
        description: Request for user id.
        content:
          application/json:
            schema:
              description: Username to log.
              type: string
              example: RubenCiranni
              minLength: 0
              maxLength: 15
              pattern: ".*"
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "404":
          $ref: "#/components/responses/NotFound"

  /photos/:
    post:
      operationId: uploadPhoto
      description: -|
        New photo upload, multiple photos possible.
      summary: Upload a new photo
      tags:
        - photos
      requestBody:
        required: true
        description: Request body for the photo
        content:
          multipart/form-data: 
            schema:            
              $ref: "#/components/schemas/Photo"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "400":
          $ref: "#/components/responses/BadRequest"

  /photos/{photoId}:
    parameters:
      - $ref: "#/components/parameters/photoId"

    delete:
      operationId: deletePhoto
      description: Delete photo operation that requires the id of the photo to be deleted.
      summary: Delete a photo that exists.
      tags:
        - photos
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /photos/{photoId}/likes/{userId}:
    parameters:
      - $ref: "#/components/parameters/photoId"
      - $ref: "#/components/parameters/userId"

    put:
      operationId: likePhoto
      description: Put a like with the identifier of the user that put the like.
      summary: Add a like to the photo.
      tags:
        - likes
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      operationId: unlikePhoto
      description: Remove like from the photo liked by the user.
      summary: Remove like from the photo.
      tags:
        - likes
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /photos/{photoId}/comments/:
    parameters:
      - $ref: "#/components/parameters/photoId"
    post:
      operationId: commentPhoto
      description: Post a comment to the photo browsed.
      summary: Add a comment to the photo.
      tags:
        - comments

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Comment"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "404":
          $ref: "#/components/responses/NotFound"

  /photos/{photoId}/comments/{commentId}:
    parameters:
      - $ref: "#/components/parameters/photoId"
      - $ref: "#/components/parameters/commentId"

    delete:
      operationId: uncommentPhoto
      description: Delete a comment from the photo browsed via its unique identifier.
      summary: Remove comment from the photo.
      tags:
        - comments
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /users/{userId}:
    parameters:
      - $ref: "#/components/parameters/userId"

    put:
      description: Set a new username for the user if the necessary authorization is present.
      summary: Set username for a user.
      operationId: setMyUserName
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              description: New name for the user.
              minLength: 0
              maxLength: 100
              example: gabrimat
              pattern: ".*"
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      operationId: deleteUser
      description: Delete user if the necessary authorization is present.
      summary: Delete a user profile.
      tags:
        - users
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /users/{userId}/stream:
    parameters:
      - $ref: "#/components/parameters/userId"

    get:
      summary: Get user's feed
      description: Retrieve the feed of the specified user.
      operationId: getMyStream
      tags:
        - users
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /users/{userId}/follows/{followId}:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/followId"

    put:
      description: Put a follow with the id of the user followed in the follows of the user.
      summary: Follow a user.
      operationId: followUser
      tags:
        - follows
      responses:
        "200":
          $ref: "#/components/responses/Created"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      description: Delete the follow from the follows of the user selected.
      summary: Unfollow a user.
      operationId: unfollowUser
      tags:
        - follows
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /users/{userId}/bans/{banId}:
    parameters:
      - $ref: "#/components/parameters/userId"
      - $ref: "#/components/parameters/banId"

    put:
      description: Put a ban with the id of the user banned in the list of the bans.
      summary: Ban a user.
      operationId: banUser
      tags:
        - bans
      responses:
        "201":
          $ref: "#/components/responses/Created"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      description: Delete the ban via user id from the ban list of the user.
      summary: Unban a user.
      operationId: unbanUser
      tags:
        - bans
      responses:
        "200":
          $ref: "#/components/responses/OK"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

components:
  responses:
    OK:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessage"
    Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessage"
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessage"
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessage"
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResponseMessage"

  parameters:
    photoId:
      in: path
      name: photoId
      required: true
      schema:
        description: Id of the photo.
        type: integer
    userId:
      in: path
      name: userId
      required: true
      schema:
        description: Id of the user.
        type: integer
    followId:
      in: path
      name: followId
      required: true
      schema:
        description: Id of the user at the end of the follow relation.
        type: integer
    banId:
      in: path
      name: banId
      required: true
      schema:
        description: Id of the user at the end of the ban relation.
        type: integer
    commentId:
      in: path
      name: commentId
      required: true
      schema:
        description: Id of the comment on the photo.
        type: integer
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: string # optional, arbitrary value for documentation purposes

  schemas:
    ResponseMessage:
      type: object
      description: General response
      properties:
        code:
          type: string
          description: Code of the response.
          minLength: 0
          maxLength: 4
          example: "404"
          pattern: ".*"
        message:
          type: string
          description: Message of the response.
          minLength: 0
          maxLength: 1000
          example: "Error element not found"
          pattern: ".*"
    User:
      title: User
      description: User profile of a user.
      type: object
      properties:
        name:
          description: Name of the user.
          type: string
          example: Gabriele Matiddi
          minLength: 0
          maxLength: 100
          pattern: ".*"
    Photo:
      title: Photo
      description: This object represents a photo in the system.
      type: object
      properties:
        file:
          type: string
          format: binary
          description: The photo file
          example: 1010
          minLength: 0
          maxLength: 100000000
          pattern: ".*"
        additionalData:
          type: object
          properties:
            Caption:
              description: Photo Caption written by the user.
              type: string
              example: Bella giornata!
              pattern: ".*"
              minLength: 0
              maxLength: 100
            PublisherId:
              description: Id of the Publisher of the photo.
              type: integer
              example: 123
    PhotoList:
      title: PhotoList
      description: list of Photos
      type: array
      items:
        $ref: "#/components/schemas/Photo"
      minItems: 0
      maxItems: 1000
      #Missing example
    Comment:
      title: Comment
      description: Comment of a published photo.
      type: object
      properties:
        photoId:
          description: Photo unique identifier where the comment belongs.
          type: integer
          example: 1234
          readOnly: true
        commenterId:
          description: User identifier for the user that published the comment.
          type: integer
          example: 1324
          readOnly: true
        text_comment:
          description: Text content of the comment.
          type: string
          example: Nice photo!
          minLength: 0
          maxLength: 1000
          pattern: ".*"

security:
  - bearerAuth: []
